apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: client
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: client
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: client
    spec:
      containers:
      - image: CONTAINER_IMAGE
        imagePullPolicy: Always
        name: client
        ports:
        - containerPort: 80
        
---
apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: client
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: client
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: dev
  name: client
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: dev
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: client
              port:
                number: 80