FROM python:3.12.2

WORKDIR /code
COPY ./client/requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
COPY ./client/app /code/app
COPY grpc_compiled /code/app/grpc_compiled

EXPOSE 80
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]