version: '3.3'

services:
  client:
    build: 
      context: ./
      dockerfile: ./client/Dockerfile.local
    ports:
      - 80:80
    depends_on:
      - server

  server:
    build:
      context: ./
      dockerfile: ./server/Dockerfile.local
