FROM python:3.12.2

WORKDIR /code
COPY ./server/requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
COPY ./server/app /code/app
COPY grpc_compiled /code/app/grpc_compiled

EXPOSE 50051
CMD ["python", "/code/app/server.py"]